name: Hostel Availability Checker

on:
  schedule:
    - cron: '0 6 * * *'   # 6 AM UTC (morning check)
    - cron: '0 12 * * *'  # 12 PM UTC (afternoon check)
    - cron: '0 18 * * *'  # 6 PM UTC (evening check)
  workflow_dispatch:

jobs:
  check-hostel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chrome 100
        run: |
          wget https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_100.0.4896.60-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_100.0.4896.60-1_amd64.deb --allow-downgrades
          google-chrome --version

      - name: Install ChromeDriver 100
        run: |
          wget https://chromedriver.storage.googleapis.com/100.0.4896.20/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests selenium

      - name: Create config with secrets
        run: |
          cat > config.json << EOF
          {
            "url": "https://accommodationhub.uenr.edu.gh/",
            "check_interval_seconds": 28800,
            "use_keyword": true,
            "keyword": "available",
            "monitor_content_changes": true,
            "notification_methods": ["email"],
            "smtp": {
              "enabled": true,
              "smtp_host": "smtp.gmail.com",
              "smtp_port": 587,
              "username": "${{ secrets.EMAIL_USERNAME }}",
              "password": "${{ secrets.EMAIL_PASSWORD }}",
              "from_addr": "${{ secrets.EMAIL_USERNAME }}",
              "to_addr": "${{ secrets.EMAIL_USERNAME }}"
            },
            "timeout_seconds": 30,
            "user_agent": "hostel-notifier-github-actions/1.0",
            "state_file": "last_state.json",
            "single_run": true
          }
          EOF

      - name: Run hostel checker
        run: python hostelnotifier.py

      - name: Upload state file
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: state-file
          path: last_state.json
          retention-days: 30
